# Generated by Django 3.1.5 on 2021-05-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksheet',
            name='reason_late_entry',
            field=models.CharField(default='OnTime', max_length=200),
        ),
    ]
