# Generated by Django 3.1.5 on 2021-06-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0011_swkattendants'),
        ('swk', '0003_uploadpicturemodel'),
    ]

    operations = [
    ]
