# Generated by Django 3.1.5 on 2021-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0012_merge_20210616_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('selectzones', models.CharField(max_length=100)),
                ('selectlanes', models.CharField(max_length=100)),
                ('grievance', models.TextField()),
            ],
            options={
                'db_table': 'swk_grievance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('service_swk', models.IntegerField(default='yes')),
                ('timing_swk', models.IntegerField()),
                ('mobile_swk', models.IntegerField()),
                ('compost_kit_garden', models.IntegerField()),
                ('communicate_swk', models.IntegerField()),
                ('solid_waste_man', models.IntegerField()),
                ('service_workers', models.IntegerField()),
                ('segregation', models.IntegerField()),
                ('recycle_process', models.IntegerField()),
                ('awareness', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'swk_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupervisorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_names', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'swk_zone_supervisors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwkBubblePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bubble_id', models.IntegerField(blank=True, null=True)),
                ('spot_id', models.IntegerField(blank=True, null=True)),
                ('bubble_population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swk_bubble_population',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='date',
            field=models.DateField(help_text='Enter Date'),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='num_attendants',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='num_houses_reached',
            field=models.IntegerField(default=20, help_text='Enter Houses Reached'),
        ),
    ]
